### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Desoroxxx** [VirxEpicoder/PewDiePies-AirPods#4]
**Describe the bug**
A server crash and client

**To Reproduce**
1. Paly on a private server for you and your friends
2. Once the end of the music arrives remove the Airpods

**Expected behavior**
The server crash and all the connected client

**Desktop (please complete the following information):**
 - OS:Windows 10
 - MC 1.12.2
 - Mod version 1.1.0

**Additional context**
net.minecraft.util.ReportedException: Ticking playerat net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraftat ericcreation.pewpods.init.PlaySound.onPlayerTick(PlaySound.java:108) ~[PlaySound.class:?]at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_235_PlaySound_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]... 9 more[18:39:16]: [NetHandlerPlayServer] Desoroxxx lost connection: Internal server error

**Comment by VirxEpicoder** [comment]
Thank you for dropping this bug report! I noticed your bug report earlier and filed one for you, but thanks anyways. This bug has already been fixed in 1.2.0, which should be coming out soon.
